public class MyThreadEight extends Thread {

    // within a run() current thread means child thread
    public void run() {

        System.out.println("This Line is Excuted by Thread: " + Thread.currentThread().getName());
    }
}

/*
 * Every thread in java having some name it may be explicity provided
 * by programmer or default name generated by the JVM
 * we can change main class name
 */

class MyThreadDemoEight {
    public static void main(String[] args) {

        // within a main() current thread means main thread
        // getting the main thread name
        System.out.println("This Line is Excuted by Thread: " + Thread.currentThread().getName());
        // getting the child thread name
        MyThreadEight t8 = new MyThreadEight();
        t8.start();// staring the thread
        System.out.println("Default name provided by jvm:- " + t8.getName());

        // changeing the thread class name
        Thread.currentThread().setName("Main Thread Name is Changed :- Pawan Kalyan");
        System.out.println(Thread.currentThread().getName());

        // we get the airthmatic exception but the name of the main() will change
        System.out.println(10 / 0);
    }
}
